language: php

php:
  - 7.1.8

before_script:
  - composer self-update
  - composer install --optimize-autoloader --no-interaction
  
script:
    - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache